# Generated by Django 5.0.7 on 2024-07-26 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('short_description', models.TextField()),
                ('guest_per_room', models.IntegerField()),
                ('bed_per_room', models.IntegerField()),
                ('washroom_per_room', models.IntegerField()),
                ('price_per_room', models.IntegerField()),
                ('about', models.TextField()),
                ('additional_info', models.TextField()),
                ('check_in', models.TextField()),
                ('check_out', models.TextField()),
                ('total_rooms', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heroImage', models.TextField()),
                ('additionalImage', models.TextField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
        ),
    ]
