# Generated by Django 5.0.7 on 2024-07-28 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_remove_hotelimage_hotel_hotel_hotel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotelimage'),
        ),
    ]
